### ISSUE TITLE
[R-package] Basic Walkthrough Crashes R

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#1142]
## Environment info

* Operating System: Windows 8.1 Pro
* CPU: i7-7700HQ
* C++/Python/R version: R 3.4.3

## Error Message:

Crash

## Reproducible examples

Run https://github.com/Microsoft/LightGBM/blob/master/R-package/demo/basic_walkthrough.R

## Steps to reproduce

1. Run https://github.com/Microsoft/LightGBM/blob/master/R-package/demo/basic_walkthrough.R

@guolinke I found many other instances of crashes while trying to make custom docs (such as in examples).

**Comment by guolinke** [comment]
@Laurae2 I think we need to add some R`s test to the Travis. otherwise it is time-costing to check them manually.

**Comment by Laurae2** [comment]
See my preparation for adding pkgdown support: https://github.com/Laurae2/LightGBM/tree/pkgdown

![image](https://user-images.githubusercontent.com/9083669/34339814-97a9f928-e979-11e7-8bdc-5ae7f3770631.png)

I encountered all the crashes when trying to get demos (converted to vignettes) and examples to run.

@guolinke If we get [pkgdown](https://github.com/r-lib/pkgdown) to run successfully, it can do all the tests by itself (as long as they are under examples and vignettes).

**Comment by guolinke** [comment]
great! I will check it recently.

**Comment by guolinke** [comment]
@Laurae2 The problem is caused when feature names contains `=` symbol.
Fixed in the latest PR.

**Comment by Laurae2** [comment]
@guolinke I think it still crashes but probably in another place now.

![image](https://user-images.githubusercontent.com/9083669/35194187-a5c1a9f2-feaf-11e7-8d2f-c89d57b7afb6.png)

**Comment by guolinke** [comment]
@Laurae2 
I just try it again, and everything is fine. Can you try to clean up and re-install R package from the latest code again?

**Comment by guolinke** [comment]
@Laurae2 
oh, When `q()` R, it crashed. 
It seems there are some GC problem.

**Comment by Laurae2** [comment]
Now works properly.

Reproducible code for before/after ffeae5a:

```r
library(lightgbm)
data(agaricus.train, package = "lightgbm")
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label = train$label)
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2")
valids <- list(test = dtest)
model <- lgb.train(params,
                   dtrain,
                   100,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10)
lgb.save(model, "model.txt")
load_booster <- lgb.load(filename = "model.txt")
model_string <- model$save_model_to_string(NULL) # saves best iteration
load_booster_from_str <- lgb.load(model_str = model_string)
gc()
```
