### ISSUE TITLE
max_bin and number of unique splits for a feature

### ISSUE THREAD

**Issue by aftersought** [Microsoft/LightGBM#1144]
For a given max_bin parameter, should one expect at most max_bin / max_bin - 1 unique splits for a single continuous feature across the whole generated forest? @guolinke @chivee

**Comment by guolinke** [comment]
It is true in single tree, but not for the whole forest.

BTW, the max_bin is a limitation of num_bin. For example, for a 0/1 feature, the num_bin of that feature will be 2 even set max_bin to a large number.

**Comment by aftersought** [comment]
@guolinke I have run a fitting procedure (using python lib) with {'max_bin': 63} in Booster params, but after scanning the first tree of the model file I see 99 unique thresholds for feature 251 (snippet with 'split_values' / 'thresholds'
[SplitsExample2.txt](https://github.com/Microsoft/LightGBM/files/1587036/SplitsExample2.txt)). For completeness sake, here is the python code parsing unique threshold values

```
f = open("SplitsExample2.txt")
# parse feature ids
featureLine = f.readline()
featureLine = featureLine[featureLine.find('=') + 1:]
features = [int(x) for x in featureLine.split(' ')]
# parse split values
thresholdLine = f.readline()
thresholdLine = thresholdLine[thresholdLine.find('=') + 1:]
thresholds = [float(x) for x in thresholdLine.split(' ')]
# count unique splits
assert len(features) == len(thresholds), "wrong file"
threshUnique = np.unique([thresholds[i] for i in range(len(features)) if features[i] == 251])
print(len(threshUnique))
print(threshUnique)
```

This should be sufficient to explain what I am trying to do. If this does not look correct, I can try and produce reproducible example with toy data.

**Comment by guolinke** [comment]
@aftersought 
Sorry, I was wrong. unique splits for a feature will be smaller than num_bin only when there is only one features.

**Comment by aftersought** [comment]
@guolinke 
Could you please explain in a couple of words, how that works? I am curious because as far as I can see once the Dataset is created all the feature data going in it can be erased. Without recourse to that data, LightGBM can presumable only work with discretized splits (which are presumably limited by `max_bin` param), and cannot create new splits?
This is also collaborated somewhat by the fact that across a pretty large forest generated on a large dataset (10^8 records) I can only see at most ~1.5 * max_bin splits for a single feature.

**Comment by guolinke** [comment]
For example, assume there are two independent features, A and B.
If the root is split by Feature A, and data is partitioned evenly in its two children. Then in these two subtrees, we both can use Feature B to split independently. 

As a result, there is a combination. The total number of unique split is exponentially growth with number of features.

**Comment by aftersought** [comment]
@guolinke 
I am not sure we are talking about the same thing. Suppose we have two features, A and B, and max_bin=2. How many unique threshold values for feature A can we see in dataset? For example, if a main node is split by feature A on `threshold=1`, can the left child then be split on feature A on some other threshold (not 1)? And if yes, where does the value of that threshold come from if the underlying feature data is already erased by the user and `Dataset` only stores discrete representation (as per docs)?

**Comment by guolinke** [comment]
a simple example with 4 samples, with two features, whose num_bin=2.

Id A B
1 0 0
2 0 1
3 1 0
4 1 1


if root is split by feature A, then there are one split for Feature A, two splits for feature B.
if root is split by feature B, then there are one split for Feature B, two splits for feature A.
So for both Feature A and B, the number of unique splits could be 1 and 2. 

if there are 3 feature with num_bin=2, the number of splits of any feature could be 1, 2, 4.
...

**Comment by guolinke** [comment]
Sorry, I think I mis-understand your question. 
You are counting the same thresholds in different nodes as the one unique split?

**Comment by aftersought** [comment]
@guolinke Yes, exactly! If they have same feature index.

**Comment by guolinke** [comment]
okay, in that case, it should be smaller than `max_bin` for numerical features. 
I think maybe there are somethings wrong in your training. 
I remember we had a bug that the `max_bin` cannot be passed correctly in python package. 
you can try the latest code.

**Comment by aftersought** [comment]
@guolinke My current LightGBM version is 2.0.11. I will try to produce a simpler example then.

**Comment by guolinke** [comment]
@aftersought I remember that issue is fixed after 2.0.11. So you can try the new version I just update today.

**Comment by aftersought** [comment]
@guolinke Unfortunately I still see the same issue with v2.0.12 ('max_bin':63, actual maximum of unique threshold for one of the factors in the very first tree: 81). I will try to produce a minimal example, as I am not sure what am I doing wrong.

**Comment by aftersought** [comment]
@guolinke Here you go

```
import gc
import numpy as np
import lightgbm as lgb

obs_count = 10000000
factor_count = 10
max_bin = 63

def generate():

    # generate training data
    factors_train = np.random.randn(obs_count, factor_count)
    target_train = np.sum(factors_train, axis=1)
    lgb_train = lgb.Dataset(factors_train, target_train, free_raw_data=True)
    lgb_train.raw_data = None

    # train and save model
    params = {
        'objective': 'regression_l2',
        'learning_rate': 0.01,
        'metric': 'l2',
        'verbose': 0,
        'num_threads': 4,
        'num_leaves': 10000,
        'min_data_in_leaf': 1000,
        'max_bin': max_bin
    }
    booster = lgb.train(params, lgb_train, num_boost_round=1)
    booster.save_model("model.txt")


def check():
    current_tree = None
    features = None
    thresholds = None

    # read the model and find the maximum number of splits
    for line in open("model.txt"):
        if line.startswith("Tree="):
            current_tree = int(line[line.find('=') + 1:])
        elif line.startswith("split_feature="):
            if not current_tree:
                continue
            # parse feature ids
            line = line[line.find('=') + 1:]
            features = [int(x) for x in line.split(' ')]
        elif line.startswith("threshold="):
            if not current_tree:
                continue
            # parse split values
            line = line[line.find('=') + 1:]
            thresholds = [float(x) for x in line.split(' ')]
        elif len(line) <= 1:
            # count unique splits for each factor
            if features and thresholds:
                assert len(features) == len(thresholds), "wrong file"
                for f in range(factor_count):
                    thresholds_unique = np.unique([thresholds[i] for i in range(len(features)) if features[i] == f])
                    if len(thresholds_unique) > max_bin:
                        print("Factor {} has {} unique splits in tree {}".format(
                            f, len(thresholds_unique), current_tree))
                        print(thresholds_unique)
                        return False
            # reset for next tree
            current_tree = None
            features = None
            thresholds = None
    return True

generate()
check()
```

My observation is that there are never more than (2 * max_bin) unique splits.

**Comment by guolinke** [comment]
@aftersought 
I run your code many times, and it always return `True`. 
![image](https://user-images.githubusercontent.com/16040950/34367501-6126f6da-eae6-11e7-83f9-167c61b40204.png)

**Comment by aftersought** [comment]
@guolinke Apologies, this was for an older version of the package. I have updated the code in place for the last version, please check.

**Comment by guolinke** [comment]
@aftersought 
you didn't pass ```params``` to Dataset object. As a result, the max_bin is not be passed. 

@StrikerRUS @wxchan Do you think we should pass the `params` in `lgb.train` to non-constructed Datasets ?

**Comment by aftersought** [comment]
@guolinke Yes, that solves it for the test (and presumably for my main dataset. will check). Were `params` always part of Dataset constructor? Anyway, thanks for checking.
