### ISSUE TITLE
[R-package] [Fatal] Check failed: num_data > 0

### ISSUE THREAD

**Issue by vspinu** [Microsoft/LightGBM#1344]
## Environment info
 setting  value                                             
 version  R Under development (unstable) (2018-02-17 r74265)
 os       Ubuntu 16.04.4 LTS                                
 system   x86_64, linux-gnu                                 
 ui       X11                                               
 language                                                   
 collate  en_GB.UTF-8                                       
 tz       Europe/Amsterdam                                  
 date     2018-04-27                                        

 lightgbm    * 2.1.0       2018-04-26 local                            

## Error Message:

```
[LightGBM] [Fatal] Check failed: num_data > 0 at /home/vspinu/VC/LightGBM/R-package/src/src/io/dataset.cpp, line 27 .

Error in dtrain$construct() : 
  lgb.Dataset.construct: cannot create Dataset handle
```

## Reproducible examples

```R
mat <- structure(c(1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 3),
                 .Dim = c(10L, 2L),
                 .Dimnames = list(NULL, c("holid_nat", "holid_state")))
label <- 1:10
dtrain <- lgb.Dataset(mat, label = label)
dtrain$construct()
```

Could be related to #1341 and #1280.

**Comment by guolinke** [comment]
you can use 3.4.x R for now.

**Comment by guolinke** [comment]
fixed in the latest commit

**Comment by vspinu** [comment]
This doesn't seem to be fixed.  I am still seeing it with the most recent master:

```R
─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R Under development (unstable) (2018-12-01 r75733)
 os       Ubuntu 18.04.1 LTS
 system   x86_64, linux-gnu
 ui       X11
 language
 collate  en_GB.UTF-8
 ctype    en_GB.UTF-8
 tz       Europe/Amsterdam
 date     2019-01-11

─ Packages ───────────────────────────────────────────────────────────────────
 package     * version    date       lib source
 assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.0)
 backports     1.1.2      2017-12-13 [1] CRAN (R 3.5.0)
 callr         3.0.0.9002 2018-12-03 [1] Github (r-lib/callr@1cbce9d)
 cli           1.0.1      2018-09-25 [1] CRAN (R 3.6.0)
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.0)
 data.table    1.11.9     2018-12-03 [1] Github (Rdatatable/data.table@e6913a4)
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)
 devtools      2.0.1.9000 2018-12-03 [1] Github (r-lib/devtools@a6bbe87)
 digest        0.6.18     2018-10-10 [1] CRAN (R 3.6.0)
 fs            1.2.6      2018-08-23 [1] CRAN (R 3.6.0)
 glue          1.3.0      2018-07-17 [1] CRAN (R 3.6.0)
 jsonlite      1.6        2018-12-07 [1] CRAN (R 3.6.0)
 lightgbm    * 2.2.3      2019-01-10 [1] local
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.0)
 memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.0)
 pkgbuild      1.0.2.9000 2018-12-03 [1] Github (r-lib/pkgbuild@6e4ebdf)
 pkgload       1.0.1.9000 2018-12-03 [1] Github (r-lib/pkgload@0ef4f58)
 prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.0)
 processx      3.2.0.9001 2018-12-03 [1] Github (r-lib/processx@366475b)
 ps            1.2.1      2018-11-06 [1] CRAN (R 3.6.0)
 R6          * 2.3.0      2018-10-04 [1] CRAN (R 3.6.0)
 Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.6.0)
 remotes       2.0.2.9000 2018-12-03 [1] Github (r-lib/remotes@2e3bf35)
 rlang         0.3.0.9001 2018-12-18 [1] Github (r-lib/rlang@327740f)
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)
 testthat      2.0.0      2017-12-13 [1] CRAN (R 3.5.0)
 usethis       1.4.0      2018-08-14 [1] CRAN (R 3.6.0)
 withr         2.1.2.9000 2018-10-23 [1] Github (jimhester/withr@be57595)

[1] /home/vspinu/.lib/3.6.0
[2] /home/vspinu/bin/R-latest/library
```

**Comment by vspinu** [comment]
Nevermind. I probably had some binaries lying around in the source dir which were copied over with the new installation procedure.
