### ISSUE TITLE
GPU error on x86_64 with Tesla V100

### ISSUE THREAD

**Issue by ironv** [Microsoft/LightGBM#1998]
I am running a docker container with the following details:

    OS:     Ubuntu 16.04.5 LTS
    GPU:    Tesla V100-SXM2
    CUDA:   10.0.130
    PYTHON: 3.5.2

The GPU works fine when I use it with Keras, Numba, etc.  I downloaded LightGBM and compiled (with GPU flags).  There are no errors that I see at any step.  I can run from python the CPU version with num_thread = 28 and that works perfectly.  However, when I add  device='gpu' and gpu_device_id=0, I get the following error:  ` LightGBMError: No OpenCL device found`.  Details of the output from the compilation steps, and the stack trace for the error are given below.  I would appreciate any suggestions for how I could get this to work.  Thx.

Also note that the container did not originally have lightgbm.  So, it is not that there are two versions and I am seeing the wrong one.  When I run `import lightgbm as lgb` and then `lgb.__file__` I do get the correct location.

**Comment by ironv** [comment]
Looking at an older [post](https://github.com/Microsoft/LightGBM/issues/586), it appears that running the following helped  `mkdir -p /etc/OpenCL/vendors && \ echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd`.  Is this required even if `OpenCL_LIBRARY` and `OpenCL_INCLUDE_DIR` are mentioned in the `cmake` step above? Thx.

**Comment by mayer79** [comment]
@ironv: did you run a clean session after changing `max_bin`?

**Comment by ironv** [comment]
@mayer79 I have been running clean sessions every time.  So, in my Jupyter notebook I always run with "Restart and Run All".

I went back to the examples provided [here](https://github.com/Microsoft/LightGBM/blob/master/docs/GPU-Performance.rst) to see if that would work.  My code is shown below and I am happy to report that example is working and the GPU is giving me a 3x speedup.

Unfortunately, my instance is still not working and I get the error reported above.  Working perfectly with CPU but still giving the error above with GPU.  I thought a difference was lgb.cv versus lgb.train but higgs works perfectly with lgb.cv using GPU.  One key difference is that my input matrix is a lot wider (9000+ columns).  Could that be an issue?  And because of that would I need to set some other param?


    import lightgbm as lgb
    import numpy as np
    from sklearn.metrics import roc_auc_score

    with open('higgs.train') as f:
        y_train = np.array([x[0] for x in f])
    with open('higgs.test') as f:
        y_test = np.array([x[0] for x in f])

    train_lgb = lgb.Dataset('higgs.train').construct()
    print('#row in train_lgb: {:,}'.format(train_lgb.num_data()))

    ##########GPU

    param_final = dict(max_bin=63, num_leaves=255, num_iterations=500, learning_rate=.1, tree_learner='serial', 
                      min_data_in_leaf=100, num_threads=16, device='gpu')

    model_gbm = lgb.train(param_final, train_lgb, verbose_eval=False)

        #CPU times: user 17min 33s, sys: 28.8 s, total: 18min 2s
        #Wall time: 1min 12s

    print('train: {}'.format(roc_auc_score(y_train, model_gbm.predict('higgs.train', SVMLight=True))))
    print('test: {}'.format(roc_auc_score(y_test, model_gbm.predict('higgs.test', SVMLight=True))))

        #AUC train: 0.8498480556891181
        #AUC test: 0.8421583671697879

    ##########CPU (run as a clean session after commenting out GPU part)

    param_final = dict(num_leaves=255, num_iterations=500, learning_rate=.1, tree_learner='serial', 
                      min_data_in_leaf=100, num_threads=16)

    model_gbm = lgb.train(param_final, train_lgb, verbose_eval=False)

        #CPU times: user 54min 8s, sys: 19.4 s, total: 54min 28s
        #Wall time: 3min 27s

    print('train: {}'.format(roc_auc_score(y_train, model_gbm.predict('higgs.train', SVMLight=True))))
    print('test: {}'.format(roc_auc_score(y_test, model_gbm.predict('higgs.test', SVMLight=True))))

        #AUC train: 0.8498480563639954
        #AUC test: 0.8421585516951305

**Comment by ironv** [comment]
I can confirm that the issue is the number of features in the input matrix.  I tried the following `train_lgb = lgb.Dataset(train_csc[:,:5800], train_pd['is_case'].values).construct()`, and that works fine.  When that number is changed to `5900`  I get and exception `LightGBMError: bin size 272 cannot run on GPU`

**Comment by ironv** [comment]
Closing issue since the originally reported issue has been addressed.  Moving the wide matrix problem to another issue.

**Comment by AnakTeka** [comment]
> Closing issue since the originally reported issue has been addressed. Moving the wide matrix problem to another issue.

How do you fix this? I have exactly same issue error `LightGBMError: No OpenCL device found` although I have successfully compile LightGBM with `--gpu` param

> Looking at an older [post](https://github.com/Microsoft/LightGBM/issues/586), it appears that running the following helped `mkdir -p /etc/OpenCL/vendors && \ echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd`. Is this required even if `OpenCL_LIBRARY` and `OpenCL_INCLUDE_DIR` are mentioned in the `cmake` step above? Thx.

And this one does not fix my issue.
