### ISSUE TITLE
segmentation fault encountered when 'boosting = goss'

### ISSUE THREAD

**Issue by fengxh0628** [microsoft/LightGBM#3074]
## How you are using LightGBM?

LightGBM component: Python package

## Environment info

Operating System: ubuntu-20.04-desktop-amd64

CPU/GPU model: CPU

C++ compiler version: 9.3.0

CMake version: 3.16.3

Java version: N/A

Python version: 3.8.2

R version: N/A

Other: N/A

LightGBM version or commit hash: 2.3.2

## Error message and / or logs

Segmentation fault (core dumped)

## Reproducible example(s)

from sklearn.datasets import fetch_california_housing
import lightgbm as lgbm

X, y = fetch_california_housing(return_X_y=True)
param = { 'boosting': 'goss' }
dataset = lgbm.Dataset(X, y)
model = lgbm.train(param, dataset)

## Steps to reproduce
I updated lightgbm on my machine today. However, when I set boosting to goss, segmentation fault was encountered. Setting boosting to gbdt worked well.

**Comment by guolinke** [comment]
fixed in f155379c1fe4e53d5d1c7fd195987a8d3aec4331

**Comment by fengxh0628** [comment]
thank you for your quick fix @guolinke 

I tested but still failed:
`[LightGBM] [Fatal] Check failed: (best_split_info.left_count) > (0) at /home/fengxh/Downloads/LightGBM/src/treelearner/serial_tree_learner.cpp, line 622 .`

Any idea how i can avoid it?

**Comment by guolinke** [comment]
@fengxh0628 can you provide a reproduce example for this case? thanks

**Comment by fengxh0628** [comment]
Just a simple case:

```
from sklearn.datasets import fetch_california_housing
import lightgbm as lgbm

X, y = fetch_california_housing(return_X_y=True)
param = { 'boosting': 'goss' }
dataset = lgbm.Dataset(X, y)
model = lgbm.train(param, dataset)
```

Thanks.

**Comment by guolinke** [comment]
@fengxh0628 can you try the fix in #3077 ?

**Comment by fengxh0628** [comment]
> @fengxh0628 can you try the fix in #3077 ?

It worked well. Thanks.
