### ISSUE TITLE
How to stop lightgbm verbose in python

### ISSUE THREAD

**Issue by nirupamkar** [microsoft/LightGBM#4052]
Hi, with the latest release I am facing issue in stopping verbose altogether while training the model. Could anyone pls help me on this?

**Comment by shiyu1994** [comment]
@nirupamkar Thanks for using LightGBM. Have you tried setting `verbose` to a negative integer?

**Comment by nirupamkar** [comment]
Earlier it used to stop the logs, right now it is showing more logs.

**Comment by StrikerRUS** [comment]
I guess it should be fixed by #3742. Please try the nightly release.

**Comment by joshi-abhishek** [comment]
#3742 didn't fix this...And this one is also closed.. 
This log issue keeps popping up with every release..Do we have a fix yet?
